name: reminder-app
title: Reminder App
version: '1.0'
summary: A simple reminder application with system tray integration
description: |
  Reminder App is a desktop application to manage your daily reminders 
  with notifications and system tray integration. Features include:
  
  * Create and manage reminders with customizable schedules
  * System tray integration for easy access
  * Desktop notifications when reminders are due
  * Persistent storage of your reminders

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: [amd64]

apps:
  reminder-app:
    command: usr/bin/reminder
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network
      - gsettings
      - audio-playback
      - unity7
    slots:
      - dbus-reminder
    daemon: simple
    autostart: reminder.desktop

slots:
  dbus-reminder:
    interface: dbus
    bus: session
    name: com.ubuntu.reminder

parts:
  reminder:
    plugin: dump
    source: .
    build-packages:
      - g++
      - pkg-config
      - libgtkmm-3.0-dev
      - libnotify-dev
      - libsqlite3-dev
      - libayatana-appindicator3-dev
    override-build: |
      set -xe
      # Create build directory
      mkdir -p build
      cd build
      
      # Get compiler flags
      CXX_FLAGS=$(pkg-config --cflags gtkmm-3.0 libnotify ayatana-appindicator3-0.1)
      LD_FLAGS=$(pkg-config --libs gtkmm-3.0 libnotify ayatana-appindicator3-0.1)
      
      # Compile the source files
      echo "Compiling source files..."
      g++ -c ../src/main.cpp $CXX_FLAGS -I/usr/include/sqlite3
      g++ -c ../src/reminder_app.cpp $CXX_FLAGS -I/usr/include/sqlite3
      g++ -c ../src/reminder_popup_window.cpp $CXX_FLAGS -I/usr/include/sqlite3
      
      # Link the objects
      echo "Linking objects..."
      g++ main.o reminder_app.o reminder_popup_window.o -o reminder $LD_FLAGS -lsqlite3 -lpthread
      
      # Return to root directory
      cd ..
      
      # Create necessary directories
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps
      mkdir -p $CRAFT_PART_INSTALL/usr/share/pixmaps
      
      # Install files
      install -Dm755 build/reminder $CRAFT_PART_INSTALL/usr/bin/
      install -Dm644 data/reminder.desktop $CRAFT_PART_INSTALL/usr/share/applications/
      install -Dm644 data/reminder.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps/
      install -Dm644 data/reminder.png $CRAFT_PART_INSTALL/usr/share/pixmaps/
    stage-packages:
      - libgtkmm-3.0-1v5
      - libnotify4
      - libsqlite3-0
      - libayatana-appindicator3-1
